Fix code for get-stats for NodeJS
Error: `event` key cannot be duplicate.
Fix: `event` is supposed to receive an array. Whatever fields we need to get, we add to the list rather than defining duplicate key `event` again and again.